In [1]:
import numpy as np

In [4]:
L = [1,2,3]
#Definir una matriz o arreglo numpy
A = np.array(L)

#Ambas son iterables 
for i in L:
    print(i)
for i in A:
    print(i)
    
#Agregar cosas a la matriz
L.append(4)
#A.append(4) <- error el objeto no tiene el atributo append

#Agregar cosas a la matriz forma 2
L = L + [5]
#A = A + [4,5] error no se puede agregar un array de forma (2,) con uno de forma (3,)



    

1
2
3
1
2
3


In [7]:
L2 = []
for e in L:
    L2.append(e+e)#L2 tendra la suma de todos los elementos
print(L2)    
#Pero el signo + en numpy sirve para sumar vectores por lo que dara la suma de ambos vectores
A + A

[2, 4, 6, 8, 10]


array([2, 4, 6])

In [8]:
#Una forma de repetir dos listas es multiplicando por un valor escalar
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [9]:
#Pero en numpy funciona de forma que el 2 se multiplica a cada valor en la matriz
2*A

array([2, 4, 6])

In [10]:
#Y si elevamos el valor al cuadrado en la lista
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [11]:
#En cambio en numpy
A**2

array([1, 4, 9])

In [12]:
#Tambien hay una funcion para sacar la raiz cuadrada de una matriz
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [13]:
#Logaritmos
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [14]:
#Exponencial
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])