### Que es una matriz
 
Un vector es cualquier array de numpy pero una matriz es como una tabla donde tenemos columnas y filas 

``` python
np.array([1,2,3]) > Vector
np.array([[1,2],[3,4]]) > Matriz
``` 
Al ser una tabla con un numero definido de elementos por cada lista al hacer una matriz debemos respetar la forma de la misma si tenemos una matriz de definida asi 

```python
np.array([[1,2,3],[1,2,3],[1,2,3]])
```
Tendra la siguiente forma (3,3) que correspondera a las columnas y a cuantos filas habra en este caso 3 filas de 3 elementos otro ejemplo
```python
np.array([[1,2],[1,2],[1,2]])
```
Tendra una forma de (3,2) para accesar a la forma de la matriz cada una de estas tiene un metodo ***shape*** por el cual podremos ver como esta constituida la matriz
```python
np.array([[1,2],[1,2],[1,2]]).shape # devuelve (1,2)
```
cualquier error tanto en numpy como en librerias de deep learning que nos indiquen el atributo ***shape*** se deve a estas inconsistencias de datos en la matriz

La forma mas facil de pensar en esto esque una matriz es un vecor de 1 dimension que contiene datos, pero una matriz es un vector de n dimensiones que pueden contener datos o mas dimensiones dentro

In [3]:
#Ejemplo para accesar a las matrices
import numpy as np
A = np.array([[1,2],[1,2],[1,2]])
L = [[1,2],[1,2],[1,2]]

In [4]:
#Para acceder a la primera lista de la lista usamos esto
L[0]

[1, 2]

In [6]:
#Y para el subindice usamos esto
L[0][0]

1

In [7]:
#Y en numpy para el primer indice se hace de la misma forma 
A[0]

array([1, 2])

In [8]:
#Pero para el subindice debemos hacer lo siguiente
A[0,0]

1

In [9]:
#Aunque igual funciona la misma forma de la lista
A[0][0]

1

In [10]:
#Para pazarlo a matriz lo podemos hacer con el metodo matrix
matriz = np.matrix(A)

In [11]:
matriz

matrix([[1, 2],
        [1, 2],
        [1, 2]])

### Generando Matrices

Al igual que en ***matlab*** o ***wolfram*** podemos generar matrices de n dimensiones solo con una linea de codigo hasta ahora estabamos haciendo esto

```python
   np.array([1,2,3])
```
Pero hay una forma de generar esta listas con zeros numeros leatorios o con un elemento ahora lo veremos

In [17]:
#Si queremos una array de tamaño 10 con zeros tendremos hacer esto
A = np.zeros(10)

In [18]:
A

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# O si queremos tomar otra dimension de lo tenemos que pasar en forma de tupla
# Donde n sera el numero de elementos y d el numero de dimensiones
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
#Y tenemos una funcion para hacerlo con unos
O = np.ones((10,10))

In [22]:
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
#Con numeros aleatorios seria
R = np.random.random((10,10))

In [30]:
R

array([[0.66927213, 0.15457579, 0.87430381, 0.08464459, 0.20186587,
        0.91390183, 0.14899009, 0.54201759, 0.43555611, 0.94805637],
       [0.84379646, 0.05468731, 0.80610634, 0.16470344, 0.38199691,
        0.21157672, 0.16640282, 0.65751203, 0.9563996 , 0.30397697],
       [0.2578919 , 0.32359596, 0.9411166 , 0.32036315, 0.91387992,
        0.39542539, 0.24364233, 0.72958086, 0.69779316, 0.62954371],
       [0.50342348, 0.584392  , 0.90534589, 0.10761579, 0.18856852,
        0.95526802, 0.41198573, 0.8874506 , 0.82473018, 0.24197765],
       [0.44845595, 0.2663502 , 0.73893402, 0.36328435, 0.59991273,
        0.19148311, 0.47847544, 0.58736214, 0.51929975, 0.35691381],
       [0.20874583, 0.23689022, 0.87787262, 0.0486752 , 0.62466676,
        0.92945198, 0.5746834 , 0.88945016, 0.86778798, 0.89956699],
       [0.15269867, 0.18794865, 0.36257406, 0.99060162, 0.98606651,
        0.85868975, 0.95191545, 0.8185649 , 0.11487496, 0.17250338],
       [0.39524602, 0.64055541, 0.549099 

### Numeros aleatorios

Como podemos ver el ejemplo de arriba nos dio numeros aleatorios menores que 0, distribuidos de forma **uniforme** pero tenemos mas tipos de distribuciones como la distribucion **Gausiana**

In [32]:
G = np.random.randn((10,10))

TypeError: 'tuple' object cannot be interpreted as an integer

Este error se origina porque la funcion solo lee enteros y una tupla no es interpretable como un entero en este caso debemos darle los valores de la siguiente forma

In [33]:
G = np.random.randn(10,10)

In [34]:
G

array([[-1.44263393,  0.4414293 ,  0.36045602, -0.4982783 ,  0.55520868,
         1.07031686,  2.83567873, -1.74019108,  0.77588883,  0.15750632],
       [-0.96924123,  0.39137062, -0.81351657, -1.41456401, -0.28572992,
        -0.96051658, -1.89031654, -0.43151988, -0.05974581, -0.19617502],
       [-0.04654642, -0.62204645,  0.29157281,  0.29300596, -0.81342432,
        -0.02432311,  0.81670941, -0.83838403, -1.52978054, -2.05801547],
       [-0.33431481, -0.20569019, -0.3751574 , -1.26231084, -1.43629854,
         0.36471094,  1.60645023,  0.90118603,  0.33760095, -1.65482571],
       [ 0.55383798, -0.76911047, -0.81551025, -0.39047729, -0.52681456,
        -0.58040034,  0.33015551, -0.57225741, -1.04060361,  0.96843632],
       [-0.51552794,  0.76667214,  1.51230345,  0.31971714,  1.17130382,
        -1.26839016,  0.07382881,  0.36102918, -0.06277792,  0.30960952],
       [ 1.43887372, -0.91308795, -0.3156212 ,  1.21764992, -2.47497477,
        -0.66023277,  0.73022826,  1.64594269

Y aqui tenemos nuestra matriz de distribuicion ***Gaussiana*** Lo que significa que seran numeros entre 0, 2

Ahora veremos que numpy nos ofrece funciones para el analisis estadistico para eso haremos algunos calculo

In [35]:
#Promedio
G.mean()

-0.06686755025187123

In [36]:
#Variante
G.var()

1.006099298397912